## Regular lattice and spatial weight matrix

Spot based data is collected along a regular spaced grid where all sample areas have the same size. Such a grid is also called a regular lattice. In more rigorous terms the data $Y$ is a realisation of a random variable fixed along a lattice $D$. The lattice $D$ does not have to be regular but in the scope of spot based data it is. Spot-based data is generated by a defined sampling strategy, whereas point pattern data is the result of a stochastic process [@zuurAnalysingEcologicalData2007].

The lattice is composed of individual spatial units

$$D = \{A_1, A_2,...,A_n\}$$

where these units do not overlap

$$A_i \cap A_j = \emptyset \forall i \neq j$$

The data is then a random variable of the spatial unit along the lattice

$$Y_i = Y(A_i)$$

Most lattice data analysis technique build on the concept of neighbours. Therefore, the spatial relationship can be modelled with e.g. a spatial weight matrix $W$. There are a lot of ways to define a spatial weight matrix $W$. For example, the spatial weight matrix can be defined as a binary contiguity matrix where adjacent units are indicated by one and non-adjacent units as zero.

$$w_{ij} = \begin{cases} 1 \text{ if } A_i \text{ and } A_j \text{ are adjacent}\\ 0 \text{ otw} \end{cases}$$

other options to specify the weight matrix $W$ are mentioned in @zuurAnalysingEcologicalData2007. 

`Voyager` has a special function for the construction of the weight matrix in Visium data `findVisiumGraph`. This function defines the neigbours to be the surrounding spots.

::: {.panel-tabset}

### `R`

```{r}
# there is an empty spot we have to exclude as it has no neighbours
sfe <- sfe[, colnames(sfe) != "GAGATCTGCTTGGCAT-1"]

# construct the weight matrix using the Voyager function
colGraph(sfe, "visium") <- findVisiumGraph(sfe)
colGraph(sfe, "binary") <- findVisiumGraph(sfe, style = "B")

plotColGraph(sfe,
  colGraphName = colGraphName
) + theme_void()
```
### `Python`

```{python}
sq.gr.spatial_neighbors(adata, n_neighs=6, coord_type="grid")
spatial_weights = W.from_sparse(adata.obsp['spatial_connectivities'])

# define a wider neighbourhood graph - result is more smoothed
sq.gr.spatial_neighbors(adata, n_neighs=50, coord_type="grid", key_added="wide_spatial")
spatial_weights_wide = W.from_sparse(adata.obsp["wide_spatial_connectivities"])

fig, ax = plt.subplots(1, 1, figsize=(5, 5))
sq.pl.spatial_scatter(
    adata[adata.obsp["spatial_connectivities"].nonzero()[0], :],
    connectivity_key="spatial_connectivities",
    size=0.1,
    na_color="black",
    edges_color="black",
    edges_width=0.1,
    shape=None,
    library_id="spatial",
    ax=ax,
    fig=fig,
)

# remove unconnected spots
adata = adata[adata.obsp["spatial_connectivities"].sum(1).A1 > 0, :]

ax.set_axis_off()
fig.suptitle("Connectivity grid", size=10, y=0.9)
fig.set_dpi(200)
```

:::
