# Preamble

## Dependencies

```{r}
#| label: load-libs
#| message: false
#| warning: false
#| results: hide
source("utils.R")
theme_set(theme_light())
```

## Setup and Preprocessing

```{r}
#| label: load-data
# taken from https://pachterlab.github.io/voyager/articles/visium_10x.html
#spe_vis <- readRDS("../data/spe_spot.rds")
#spe_vis

sfe_full <- SFEData::McKellarMuscleData(dataset = "full")

sfe_full <- mirrorImg(sfe_full, sample_id = "Vis5A", image_id = "lowres")
sfe <- sfe_full[,colData(sfe_full)$in_tissue]
sfe <- sfe[rowSums(counts(sfe)) > 0,]

#perform normalisation 
sfe <- scater::logNormCounts(sfe)

colGraph(sfe, "visium") <- findVisiumGraph(sfe)
```

Given this data from McKellar et al. we choose two genes to analyse henceforth, named _Mdk_ (ENSMUSG00000027239) and _Ncl_ (ENSMUSG00000026234) [@mckellarLargescaleIntegrationSinglecell2021]. 

```{r}
MdK <- "ENSMUSG00000027239"
NcI <- "ENSMUSG00000026234"
```

```{r}
features <- c("ENSMUSG00000027239", "ENSMUSG00000026234") # MdK, Ncl
colGraphName <- "visium"
colGeometryName <- "spotPoly"
segmentation <- "spotPoly"
```

{{< include theory/02-theory-reg-lattice.qmd >}}

{{< include theory/05-theory-multivar-lattice.qmd >}}

## Session info

```{r}
#| label: session-info
sessionInfo()
```
