project: 
  type: website
  execute-dir: file
  output-dir: ../docs
  render:
    - "00-*.qmd"
    - "!theory/"
bibliography: ../misc/PASTA.bib

execute: 
  cache: false
  warning: false
  message: false

format:
  html:
    theme: lux
    toc: true
    toc-depth: 3
    standalone: true
    embed-resources: true
    code-fold: show
    code-summary: "Show the code"
    code-tools: true
    
editor_options: 
  chunk_output_type: console

website:
  back-to-top-navigation: true
  reader-mode: true
#  announcement:    
#      icon: info-circle    
#      dismissable: false  
#      content: "This website is still under active development - all content subject to change"   
#      type: primary    
#      position: below-navbar
#      page-navigation: true
  body-footer: | 
    ©2024 The `pasta` authors.\n
    Content is published under [Creative Commons CC-BY-4.0 License](https://creativecommons.org/licenses/by/4.0/) for the text 
    and [GPL-3 License](https://www.gnu.org/licenses/gpl-3.0.html) for any code.
  repo-url: https://github.com/robinsonlabuzh/pasta
  repo-actions: [source, issue]
  repo-subdir: code
  navbar:
    search: true
    tools:
    left:
      - text: "Home"
        file: 00-home.qmd
      - text: "About"
        file: 00-about.qmd
      - text: "Setup"
        file: 00-setup.qmd
      - sidebar:overview
      - sidebar:imaging
      - sidebar:HTS

  sidebar:
    - id: overview
      title: "Overview"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - text: "---"
        - text: "Overview Point Pattern-based Methods"
          file: 00-overview-ppSOD.qmd
        - text: "Overview Lattice-based Methods"
          file: 00-overview-latSOD.qmd
    - id: imaging 
      title: "Imaging-based Data"
      style: "docked"
      background: light
      collapse-level: 3
      contents: 
        - text: "---"
        - section: "Univariate Methods"
        - text: "Point Pattern-based Methods"
         file: 01-imaging-univar-ppSOD.qmd
        - text: "Lattice-based Methods"
         file: 02-imaging-univar-latSOD.qmd
        - text: "---"
        - section: "Multivariate Methods"
        - text: "Point Pattern-based Methods"
         file: 03-imaging-multivar-ppSOD.qmd
        - text: "Lattice-based Methods"
         file: 04-imaging-multivar-latSOD.qmd
          
    - id: HTS
      title: "HTS-based Data"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
       - text: "---"
       - section: "Univariate Methods"
       - text: "Lattice-based Methods"
         file: 05-HTS-univar-latSOD.qmd
       - text: "---"
       - section: "Multivariate Methods"
       - text: "Lattice-based Methods"
          file: 06-HTS-multivar-latSOD.qmd

date: last-modified	
